feat (dash direct): login
dashpay/dash-wallet pull request #1068
Opened 2022-12-06 13:44 UTC by hadia

## Issue being fixed or feature implemented

Add sign in dialog for dashdirect Api
## Related PR's and Dependencies

## Screenshots / Videos

## How Has This Been Tested?

- [ ] QA (Mobile Team)

## Checklist:

- [ ] I have performed a self-review of my own code and added comments where necessary
- [ ] I have added or updated relevant unit/integration/functional/e2e tests

2022-12-06 14:09 UTC, Syn-McJ requested changes
Some changes needed.

2022-12-06 14:09 UTC, Syn-McJ commented on features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/SearchFragment.kt
> +        }
The pattern of calling a function and observing result in `LiveData` is not great. It makes the execution flow more complicated and hard to track.

Instead, simply call a suspend function in a `lifecycleScope` and process the result.

2022-12-06 14:09 UTC, Syn-McJ commented on features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ExploreViewModel.kt
> +        get() = _dashDirectSignIn
You don't need this. See below.

2022-12-06 14:09 UTC, Syn-McJ commented on features/exploredash/src/main/java/org/dash/wallet/features/exploredash/ui/ExploreViewModel.kt
> +        viewModelScope.launch {
Just make `signInToDashDirect` suspend and return the result directly. See below.

2022-12-06 15:05 UTC, Syn-McJ approved these changes
This is better. Some more points to improve in the future:
- `runBlocking` usage is discourage. It's better to have the method that deals with settings as `suspend`. Reading from prefs is a IO operation and should be treated in an async manner.
- Returning `ResponseResource` from the viewModel method is unnecessary. Just return the result or throw an error, then `try/catch` in the caller.

2022-12-06 15:39 UTC, HashEngineering commented
The base branch is called `feature/DashDirect` which doesn't follow our `feature-*` nameing scheme which is required to activate CI.

2022-12-17 02:01 UTC, HashEngineering commented
new branch created named `feature-dashdirect`

2022-12-17 02:02 UTC, HashEngineering approved these changes

2022-12-17 02:03 UTC, merged