feat :Create Private Username
dashpay/dash-wallet pull request #1122
Opened 2023-05-09 10:53 UTC by hadia

## Issue being fixed or feature implemented

- The user should be given the option to create their username with up to 3 levels of privacy
- Firebase events should be logged 

## Related PR's and Dependencies

## Screenshots / Videos

## How Has This Been Tested?

- [ ] QA (Mobile Team)

## Checklist:

- [ ] I have performed a self-review of my own code and added comments where necessary
- [ ] I have added or updated relevant unit/integration/functional/e2e tests

2023-05-09 12:30 UTC, Syn-McJ requested changes
LGTM except some string names are way too long.

2023-05-09 13:41 UTC, hadia commented on wallet/res/values/strings.xml
> +    <string name="it_would_be_very_difficult_for_advanced_users_with_any_level_of_technical_expertise_to_determine_your_transaction_history">It would be very difficult for advanced users with any lev
refactor string names

2023-05-09 14:34 UTC, Syn-McJ approved these changes

2023-05-16 00:42 UTC, HashEngineering approved these changes
Excellent

2023-05-18 00:04 UTC, merged